[package]
name = "art"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
image = "0.24.4"
palette = "0.6.1"
rand = "0.8.5"
